import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    PG_CONNECTION_URI = os.getenv("PG_CONNECTION_URI")                              # INSERT YOUT PGVector DB URI
    embed_table = "data_items"                                                      # THE TABLE TO BE USED FOR EMBEDDING (PREFIX THE NAME WITH 'data_')
    embed_model = "ibm-granite/granite-embedding-278m-multilingual"                 # Embedding model to use (from hugging face)
    ollama_model = "dolphin3"                                                       # LLM Model to use (from ollama)
    ollama_url = "http://localhost:11434"                                           # Ollama api base url
    document_dir = "data"                                                           # Location of the documents uploaded
    optimized_rag = "optimized_image_rag_llama.json"                                # Optimized rag file generated by dspy

